/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colortextile_form;

import colortextile_class.*;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Eldridge
 */
public class Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    public Main_Menu() {
        initComponents();
        this.setSize(475, 500);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search_jo = new javax.swing.JButton();
        pigments = new javax.swing.JButton();
        Close_but = new javax.swing.JButton();
        add_new_recipe1 = new javax.swing.JButton();
        add_new_recipe2 = new javax.swing.JButton();
        print_from_recipe = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Main Menu");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 355, -1));

        search_jo.setBackground(new java.awt.Color(255, 255, 255));
        search_jo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        search_jo.setText("Search,Edit and Use Added Recipe");
        search_jo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        search_jo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_jo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search_jo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_joActionPerformed(evt);
            }
        });
        jPanel1.add(search_jo, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 205, 370, 49));

        pigments.setBackground(new java.awt.Color(255, 255, 255));
        pigments.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        pigments.setText("Add Pigments");
        pigments.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        pigments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pigments.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pigments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pigmentsActionPerformed(evt);
            }
        });
        jPanel1.add(pigments, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 325, 370, 49));

        Close_but.setBackground(new java.awt.Color(255, 255, 255));
        Close_but.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Close_but.setText("Exit");
        Close_but.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        Close_but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close_but.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Close_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_butActionPerformed(evt);
            }
        });
        jPanel1.add(Close_but, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 385, 370, 49));

        add_new_recipe1.setBackground(new java.awt.Color(255, 255, 255));
        add_new_recipe1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add_new_recipe1.setText("Add New Design Recipe Order");
        add_new_recipe1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        add_new_recipe1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_new_recipe1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add_new_recipe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_recipe1ActionPerformed(evt);
            }
        });
        jPanel1.add(add_new_recipe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 85, 370, 49));

        add_new_recipe2.setBackground(new java.awt.Color(255, 255, 255));
        add_new_recipe2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add_new_recipe2.setText("Use Existing Recipe and Add new Order");
        add_new_recipe2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        add_new_recipe2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_new_recipe2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add_new_recipe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_recipe2ActionPerformed(evt);
            }
        });
        jPanel1.add(add_new_recipe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 145, 370, 49));

        print_from_recipe.setBackground(new java.awt.Color(255, 255, 255));
        print_from_recipe.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        print_from_recipe.setText("Print from Existing Recipe/s");
        print_from_recipe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        print_from_recipe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print_from_recipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        print_from_recipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_from_recipeActionPerformed(evt);
            }
        });
        jPanel1.add(print_from_recipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 265, 370, 49));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 440, 460);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 26, 460);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(450, 0, 10, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Close_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_butActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Close_butActionPerformed

    private void pigmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pigmentsActionPerformed
        // TODO add your handling code here:
        add_pigment_form new_form = new add_pigment_form();
        new_form.setVisible(true);
        //testing2.EditSearchPigmentForm new_pigment_form = new testing2.EditSearchPigmentForm();
        //new_pigment_form.setVisible(true);
    }//GEN-LAST:event_pigmentsActionPerformed

    private void search_joActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_joActionPerformed
        // TODO add your handling code here:
        SearchJOGui new_jo = new SearchJOGui();
        new_jo.setVisible(true);
    }//GEN-LAST:event_search_joActionPerformed

    private void add_new_recipe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_recipe1ActionPerformed
        // TODO add your handling code here:
        Add_new_design newDesign = new Add_new_design();
        newDesign.setVisible(true);
    }//GEN-LAST:event_add_new_recipe1ActionPerformed

    private void add_new_recipe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_recipe2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_new_recipe2ActionPerformed

    private void print_from_recipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_from_recipeActionPerformed
        // TODO add your handling code here:
        PrintForm print_design = new PrintForm();
        print_design.setVisible(true);
    }//GEN-LAST:event_print_from_recipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close_but;
    private javax.swing.JButton add_new_recipe1;
    private javax.swing.JButton add_new_recipe2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton pigments;
    private javax.swing.JButton print_from_recipe;
    private javax.swing.JButton search_jo;
    // End of variables declaration//GEN-END:variables
}
